<script lang="ts">
  import { appData } from "../model/store";
  import DateRangePicker from "./DateRangePicker.svelte";
  import {
    addAdHocShift,
    updateLedgerShift,
    removeLedgerShift,
    assignPerson,
    unassignPerson,
    setAssignmentStatus,
    reconcileAvailability,
    isPersonAvailable,
  } from "../model/ledger";
  import type { AssignmentStatus } from "../model/types";

  // --- view range (date-only strings) --------------------------------------
  const pad = (n: number) => String(n).padStart(2, "0");
  const toDateStr = (d: Date) => `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
  function addDays(d: Date, n: number): Date {
    const r = new Date(d);
    r.setDate(r.getDate() + n);
    return r;
  }
  function parseDate(s: string): Date {
    const [y, m, d] = s.split("-").map(Number);
    return new Date(y, m - 1, d);
  }

  const today = new Date();
  let rangeStart = $state(toDateStr(today));
  let rangeEnd = $state(toDateStr(addDays(today, 13)));
  let pxPerHour = $state(16);
  let selectedId = $state<string | null>(null);
  let status = $state("");

  const HOUR_MS = 3_600_000;
  const LANE_H = 50;

  const domainStart = $derived(parseDate(rangeStart));
  const domainEnd = $derived(addDays(parseDate(rangeEnd), 1)); // end day inclusive
  const totalDays = $derived(Math.max(1, Math.round((domainEnd.getTime() - domainStart.getTime()) / 86_400_000)));
  const totalWidth = $derived(totalDays * 24 * pxPerHour);

  // Lay shifts onto lanes: greedy interval partitioning so overlaps stack.
  const layout = $derived.by(() => {
    const dStart = domainStart.getTime();
    const dEnd = domainEnd.getTime();
    const visible = $appData.ledgerShifts
      .map((s) => {
        const startMs = new Date(s.start).getTime();
        const endMs = startMs + s.durationMinutes * 60_000;
        return { shift: s, startMs, endMs };
      })
      .filter((b) => b.endMs > dStart && b.startMs < dEnd)
      .sort((a, b) => a.startMs - b.startMs || a.endMs - b.endMs);

    const laneEnds: number[] = [];
    return visible.map((b) => {
      let lane = laneEnds.findIndex((end) => end <= b.startMs);
      if (lane === -1) {
        lane = laneEnds.length;
        laneEnds.push(b.endMs);
      } else {
        laneEnds[lane] = b.endMs;
      }
      const left = ((b.startMs - dStart) / HOUR_MS) * pxPerHour;
      const width = Math.max(46, (b.shift.durationMinutes / 60) * pxPerHour);
      return { ...b, lane, left, width };
    });
  });
  const laneCount = $derived(Math.max(1, ...layout.map((b) => b.lane + 1)));

  const conflicts = $derived(reconcileAvailability($appData));

  // --- selected shift helpers ----------------------------------------------
  const selected = $derived($appData.ledgerShifts.find((s) => s.id === selectedId) ?? null);
  const selectedTemplate = $derived(
    selected?.sourceTemplateId
      ? $appData.shiftTemplates.find((t) => t.id === selected.sourceTemplateId) ?? null
      : null,
  );

  function assignmentsFor(shiftId: string) {
    return $appData.ledgerAssignments
      .filter((a) => a.ledgerShiftId === shiftId)
      .map((a) => ({ a, person: $appData.persons.find((p) => p.id === a.personId) }))
      .filter((x) => x.person !== undefined);
  }
  function unassignedPeople(shiftId: string) {
    const have = new Set($appData.ledgerAssignments.filter((a) => a.ledgerShiftId === shiftId).map((a) => a.personId));
    return $appData.persons.filter((p) => !have.has(p.id));
  }

  const fmtTime = (iso: string) =>
    new Date(iso).toLocaleString(undefined, { weekday: "short", hour: "2-digit", minute: "2-digit" });
  const toInput = (iso: string) => iso.slice(0, 16);
  const fromInput = (v: string) => (v.length === 16 ? `${v}:00` : v);

  // --- actions --------------------------------------------------------------
  function doAddAdHoc() {
    const id = addAdHocShift({
      name: "New shift",
      start: `${rangeStart}T09:00:00`,
      durationMinutes: 120,
    });
    selectedId = id;
    status = "Added a shift — edit it below.";
  }

  const statusColor: Record<AssignmentStatus, string> = {
    autogenerated: "var(--text)",
    committed: "var(--accent)",
    performed: "#2e9e5b",
  };
</script>

<div class="view">
  <h2>Ledger</h2>
  <p class="hint">
    The concrete, dated timeline. Add shifts and hand-assign people; block width is
    proportional to duration and overlapping shifts stack vertically. Automatic generation
    from your templates arrives with the solver (Phase 4).
  </p>

  <div class="row" style="gap: 16px; align-items: flex-end; margin-bottom: 12px;">
    <DateRangePicker bind:start={rangeStart} bind:end={rangeEnd} />
    <button class="btn" onclick={doAddAdHoc}>+ Add shift</button>
    <div class="field">
      <span class="cap">Zoom</span>
      <input type="range" min="6" max="60" bind:value={pxPerHour} />
    </div>
  </div>

  {#if status}<p class="status-inline">{status}</p>{/if}

  {#if conflicts.length > 0}
    <div class="banner">
      <strong>{conflicts.length} availability conflict(s):</strong>
      <ul>
        {#each conflicts as c}
          <li>{c.personName} on “{c.shiftName}” ({fmtTime(c.start)}) — now outside their availability.</li>
        {/each}
      </ul>
    </div>
  {/if}

  <!-- Timeline -->
  <div class="timeline-scroll">
    <div class="timeline" style="width: {totalWidth}px;">
      <!-- day columns + labels -->
      <div class="axis" style="width: {totalWidth}px;">
        {#each Array(totalDays) as _, i}
          <div class="day-col" style="left: {i * 24 * pxPerHour}px; width: {24 * pxPerHour}px;">
            <span class="day-label">{addDays(domainStart, i).toLocaleDateString(undefined, { weekday: "short", day: "numeric", month: "short" })}</span>
          </div>
        {/each}
      </div>
      <!-- shift blocks -->
      <div class="lanes" style="height: {laneCount * LANE_H}px; width: {totalWidth}px;">
        {#each layout as b (b.shift.id)}
          <button
            class="block"
            class:selected={b.shift.id === selectedId}
            style="left: {b.left}px; width: {b.width}px; top: {b.lane * LANE_H}px;"
            onclick={() => (selectedId = b.shift.id)}
            title={b.shift.name}
          >
            <span class="block-title">{b.shift.name}</span>
            <span class="block-people">
              {#each assignmentsFor(b.shift.id) as { a, person } (person!.id)}
                <span class="dot" style="background: {statusColor[a.status]};" title="{person!.name} ({a.status})"></span>
              {/each}
            </span>
          </button>
        {/each}
        {#if layout.length === 0}
          <p class="empty" style="padding: 16px;">No shifts in this range. Use “+ Add shift” to create one.</p>
        {/if}
      </div>
    </div>
  </div>

  <!-- Detail / assignment panel -->
  {#if selected}
    <div class="card" style="margin-top: 16px;">
      <div class="card-head">
        <input
          class="grow"
          value={selected.name}
          onchange={(e) => updateLedgerShift(selected.id, { name: e.currentTarget.value.trim() })}
          style="font-size: 16px; font-weight: 600;"
        />
        <button class="btn ghost icon" onclick={() => (selectedId = null)}>Close</button>
        <button class="btn danger icon" onclick={() => { removeLedgerShift(selected.id); selectedId = null; }}>Delete shift</button>
      </div>

      <div class="row" style="gap: 16px; margin-bottom: 12px;">
        <div class="field">
          <span class="cap">Start</span>
          <input type="datetime-local" value={toInput(selected.start)} onchange={(e) => updateLedgerShift(selected.id, { start: fromInput(e.currentTarget.value) })} />
        </div>
        <div class="field">
          <span class="cap">Duration (minutes)</span>
          <input type="number" min="1" value={selected.durationMinutes} onchange={(e) => updateLedgerShift(selected.id, { durationMinutes: Number(e.currentTarget.value) })} />
        </div>
        <div class="field">
          <span class="cap">Type</span>
          <input value={selected.type} onchange={(e) => updateLedgerShift(selected.id, { type: e.currentTarget.value.trim() })} />
        </div>
      </div>

      {#if selectedTemplate}
        {@const reqs = $appData.shiftRequirements.filter((r) => r.shiftId === selectedTemplate.id)}
        {#if reqs.length > 0}
          <p class="muted" style="font-size: 13px;">
            Requires:
            {reqs.map((r) => `${r.count}× ${$appData.attributes.find((a) => a.id === r.attributeId)?.name ?? "?"}`).join(", ")}
          </p>
        {/if}
      {/if}

      <div class="field">
        <span class="cap">Assigned people</span>
        <div class="tags">
          {#each assignmentsFor(selected.id) as { a, person } (person!.id)}
            <span class="tag" style="border-color: {statusColor[a.status]};">
              {person!.name}
              {#if !isPersonAvailable($appData, person!.id, new Date(selected.start))}
                <span title="Unavailable at this time" style="color:#c0392b;">⚠</span>
              {/if}
              <select
                style="padding: 0 2px; font-size: 12px;"
                value={a.status}
                onchange={(e) => setAssignmentStatus(selected.id, person!.id, e.currentTarget.value as AssignmentStatus)}
              >
                <option value="autogenerated">auto</option>
                <option value="committed">committed</option>
                <option value="performed">performed</option>
              </select>
              <button title="Remove" onclick={() => unassignPerson(selected.id, person!.id)}>×</button>
            </span>
          {/each}

          {#if unassignedPeople(selected.id).length > 0}
            <select
              value=""
              onchange={(e) => { if (e.currentTarget.value) assignPerson(selected.id, e.currentTarget.value); e.currentTarget.value = ""; }}
            >
              <option value="" disabled selected>+ assign…</option>
              {#each unassignedPeople(selected.id) as p (p.id)}
                <option value={p.id}>{p.name}{isPersonAvailable($appData, p.id, new Date(selected.start)) ? "" : " (unavailable)"}</option>
              {/each}
            </select>
          {/if}
        </div>
      </div>
    </div>
  {/if}
</div>

<style>
  .status-inline {
    font-size: 14px;
    color: var(--text-h);
    background: var(--code-bg);
    padding: 6px 10px;
    border-radius: 6px;
    margin: 0 0 12px;
  }
  .banner {
    border: 1px solid rgba(192, 57, 43, 0.4);
    background: rgba(192, 57, 43, 0.08);
    border-radius: 8px;
    padding: 10px 14px;
    margin-bottom: 12px;
    font-size: 14px;
  }
  .banner ul {
    margin: 6px 0 0;
    padding-left: 18px;
  }
  .timeline-scroll {
    overflow-x: auto;
    border: 1px solid var(--border);
    border-radius: 8px;
    background: var(--bg);
  }
  .timeline {
    position: relative;
  }
  .axis {
    position: relative;
    height: 28px;
    border-bottom: 1px solid var(--border);
  }
  .day-col {
    position: absolute;
    top: 0;
    bottom: 0;
    border-left: 1px solid var(--border);
    box-sizing: border-box;
  }
  .day-label {
    font-size: 12px;
    color: var(--text);
    padding: 4px 6px;
    display: inline-block;
    white-space: nowrap;
  }
  .lanes {
    position: relative;
  }
  .block {
    position: absolute;
    height: 44px;
    box-sizing: border-box;
    margin: 3px 0;
    padding: 4px 6px;
    border: 1px solid var(--accent-border);
    background: var(--accent-bg);
    border-radius: 5px;
    cursor: pointer;
    overflow: hidden;
    text-align: left;
    display: flex;
    flex-direction: column;
    justify-content: space-between;
    font: inherit;
  }
  .block:hover {
    box-shadow: var(--shadow);
  }
  .block.selected {
    outline: 2px solid var(--accent);
  }
  .block-title {
    font-size: 12px;
    font-weight: 600;
    color: var(--text-h);
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }
  .block-people {
    display: flex;
    gap: 3px;
  }
  .dot {
    width: 8px;
    height: 8px;
    border-radius: 50%;
    display: inline-block;
  }
</style>
