/**
 * ledger.ts — operations on the Ledger: the authoritative timeline of concrete,
 * dated shift instances (LedgerShift) and who is on them (LedgerAssignment).
 *
 * Responsibilities:
 *  - materialize concrete shifts from templates over a date range
 *  - add ad-hoc one-off shifts and edit/delete shifts
 *  - manual (pre-)assignment and assignment-status transitions
 *  - commit autogenerated -> committed; clear autogenerated future assignments
 *  - prior-load (performed + committed) for workload/variety objectives
 *  - availability checks + reconciliation notifications
 *
 * Effective availability = union(available) minus union(unavailable), at
 * date granularity. A person with no `available` interval is treated as always
 * available (so the tool is usable before stays are entered).
 */

import { getAppData, newId } from "./store";
import { mutate } from "./mutations";
import type { AppData, AssignmentStatus, LedgerShift } from "./types";

// --- Local datetime formatting (timezone-free, seconds precision) ----------

function pad(n: number): string {
  return String(n).padStart(2, "0");
}
function fmtLocalDate(d: Date): string {
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
}
function fmtLocalDateTime(d: Date): string {
  return `${fmtLocalDate(d)}T${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`;
}

// --- Availability ----------------------------------------------------------

/**
 * Is the person effectively available at the given moment? Compared at day
 * granularity against their availability intervals.
 */
export function isPersonAvailable(data: AppData, personId: string, when: Date): boolean {
  const day = fmtLocalDate(when);
  const intervals = data.availability.filter((a) => a.personId === personId);
  const covers = (kind: "available" | "unavailable") =>
    intervals.some((a) => a.kind === kind && a.start <= day && (a.end === undefined || day <= a.end));

  const hasAvailableInterval = intervals.some((a) => a.kind === "available");
  const available = hasAvailableInterval ? covers("available") : true;
  return available && !covers("unavailable");
}

// --- Materialization -------------------------------------------------------

/**
 * Concrete LedgerShifts are produced two ways: added by hand here, or generated
 * by the solver over a date range (Phase 4). Generation will expand templates,
 * let the solver choose window-group days/times, and write the chosen shifts +
 * assignments as `autogenerated`, holding committed/performed items fixed.
 */

/** Add a one-off shift by hand. User-created shifts are firm (not solver-owned). */
export function addAdHocShift(input: {
  name: string;
  type?: string;
  start: string; // local ISO datetime
  durationMinutes: number;
}): string {
  const id = newId();
  mutate((d) =>
    d.ledgerShifts.push({
      id,
      name: input.name,
      type: input.type ?? "",
      start: input.start,
      durationMinutes: input.durationMinutes,
    }),
  );
  return id;
}

export function updateLedgerShift(id: string, patch: Partial<LedgerShift>): void {
  mutate((d) => {
    const s = d.ledgerShifts.find((x) => x.id === id);
    if (s) Object.assign(s, patch);
  });
}

/** Delete a ledger shift and its assignments. */
export function removeLedgerShift(id: string): void {
  mutate((d) => {
    d.ledgerShifts = d.ledgerShifts.filter((s) => s.id !== id);
    d.ledgerAssignments = d.ledgerAssignments.filter((a) => a.ledgerShiftId !== id);
  });
}

// --- Assignments -----------------------------------------------------------

/** Assign a person to a shift (no duplicates). Manual assignments are committed. */
export function assignPerson(
  ledgerShiftId: string,
  personId: string,
  status: AssignmentStatus = "committed",
): void {
  mutate((d) => {
    const exists = d.ledgerAssignments.some(
      (a) => a.ledgerShiftId === ledgerShiftId && a.personId === personId,
    );
    if (!exists) d.ledgerAssignments.push({ ledgerShiftId, personId, status });
  });
}

export function unassignPerson(ledgerShiftId: string, personId: string): void {
  mutate((d) => {
    d.ledgerAssignments = d.ledgerAssignments.filter(
      (a) => !(a.ledgerShiftId === ledgerShiftId && a.personId === personId),
    );
  });
}

export function setAssignmentStatus(
  ledgerShiftId: string,
  personId: string,
  status: AssignmentStatus,
): void {
  mutate((d) => {
    const a = d.ledgerAssignments.find(
      (x) => x.ledgerShiftId === ledgerShiftId && x.personId === personId,
    );
    if (a) a.status = status;
  });
}

/**
 * Promote autogenerated assignments to committed. If `afterDate` is given, only
 * assignments on shifts starting at/after it are affected. Returns the count.
 */
export function commitAutogenerated(afterDate?: Date): number {
  const data = getAppData();
  const startById = new Map(data.ledgerShifts.map((s) => [s.id, s.start]));
  const cutoff = afterDate ? fmtLocalDateTime(afterDate) : undefined;
  let count = 0;
  mutate((d) => {
    for (const a of d.ledgerAssignments) {
      if (a.status !== "autogenerated") continue;
      const start = startById.get(a.ledgerShiftId);
      if (cutoff && (start === undefined || start < cutoff)) continue;
      a.status = "committed";
      count++;
    }
  });
  return count;
}

/**
 * Remove autogenerated assignments (tentative) so generation can be re-run
 * cleanly. With `afterDate`, only those on shifts starting at/after it. Leaves
 * committed/performed untouched. Returns the count removed.
 */
export function clearAutogenerated(afterDate?: Date): number {
  const data = getAppData();
  const startById = new Map(data.ledgerShifts.map((s) => [s.id, s.start]));
  const cutoff = afterDate ? fmtLocalDateTime(afterDate) : undefined;
  let removed = 0;
  mutate((d) => {
    d.ledgerAssignments = d.ledgerAssignments.filter((a) => {
      if (a.status !== "autogenerated") return true;
      const start = startById.get(a.ledgerShiftId);
      const inScope = !cutoff || (start !== undefined && start >= cutoff);
      if (inScope) removed++;
      return !inScope;
    });
  });
  return removed;
}

// --- Prior load (history for workload/variety) -----------------------------

export interface PersonLoad {
  shifts: number;
  minutes: number;
}

/**
 * Per-person committed + performed load read from the Ledger — the history that
 * keeps someone already booked ahead from being over-loaded. With `asOf`, only
 * counts shifts starting before that moment.
 */
export function priorLoad(data: AppData, asOf?: Date): Map<string, PersonLoad> {
  const shiftById = new Map(data.ledgerShifts.map((s) => [s.id, s]));
  const cutoff = asOf ? fmtLocalDateTime(asOf) : undefined;
  const load = new Map<string, PersonLoad>();
  for (const a of data.ledgerAssignments) {
    if (a.status !== "committed" && a.status !== "performed") continue;
    const shift = shiftById.get(a.ledgerShiftId);
    if (!shift) continue;
    if (cutoff && shift.start >= cutoff) continue;
    const cur = load.get(a.personId) ?? { shifts: 0, minutes: 0 };
    cur.shifts += 1;
    cur.minutes += shift.durationMinutes;
    load.set(a.personId, cur);
  }
  return load;
}

// --- Reconciliation --------------------------------------------------------

export interface AvailabilityConflict {
  ledgerShiftId: string;
  personId: string;
  personName: string;
  shiftName: string;
  start: string;
}

/**
 * Find committed/performed assignments that now fall outside the person's
 * effective availability (e.g. after adding an unavailable interval). Surfaced
 * to the user rather than silently dropped.
 */
export function reconcileAvailability(data: AppData): AvailabilityConflict[] {
  const shiftById = new Map(data.ledgerShifts.map((s) => [s.id, s]));
  const personById = new Map(data.persons.map((p) => [p.id, p]));
  const conflicts: AvailabilityConflict[] = [];
  for (const a of data.ledgerAssignments) {
    if (a.status === "autogenerated") continue;
    const shift = shiftById.get(a.ledgerShiftId);
    if (!shift) continue;
    if (!isPersonAvailable(data, a.personId, new Date(shift.start))) {
      conflicts.push({
        ledgerShiftId: a.ledgerShiftId,
        personId: a.personId,
        personName: personById.get(a.personId)?.name ?? "?",
        shiftName: shift.name,
        start: shift.start,
      });
    }
  }
  return conflicts;
}
