/**
 * ledger.ts — operations on the Ledger: the authoritative timeline of concrete,
 * dated shift instances (LedgerShift) and who is on them (LedgerAssignment).
 *
 * Responsibilities:
 *  - materialize concrete shifts from templates over a date range
 *  - add ad-hoc one-off shifts and edit/delete shifts
 *  - manual (pre-)assignment and assignment-status transitions
 *  - commit autogenerated -> committed; clear autogenerated future assignments
 *  - prior-load (performed + committed) for workload/variety objectives
 *  - availability checks + reconciliation notifications
 *
 * Effective availability = union(available) minus union(unavailable), at
 * date granularity. A person with no `available` interval is treated as always
 * available (so the tool is usable before stays are entered).
 */

import { getAppData, newId } from "./store";
import { mutate } from "./mutations";
import type { AppData, AssignmentStatus, LedgerShift } from "./types";

// --- Local datetime formatting (timezone-free, seconds precision) ----------

function pad(n: number): string {
  return String(n).padStart(2, "0");
}
function fmtLocalDate(d: Date): string {
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
}
function fmtLocalDateTime(d: Date): string {
  return `${fmtLocalDate(d)}T${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`;
}

// --- Availability ----------------------------------------------------------

/**
 * Is the person effectively available at the given moment? Compared at day
 * granularity against their availability intervals.
 */
export function isPersonAvailable(data: AppData, personId: string, when: Date): boolean {
  const day = fmtLocalDate(when);
  const intervals = data.availability.filter((a) => a.personId === personId);
  const covers = (kind: "available" | "unavailable") =>
    intervals.some((a) => a.kind === kind && a.start <= day && (a.end === undefined || day <= a.end));

  const hasAvailableInterval = intervals.some((a) => a.kind === "available");
  const available = hasAvailableInterval ? covers("available") : true;
  return available && !covers("unavailable");
}

// --- Materialization -------------------------------------------------------

/**
 * Concrete LedgerShifts are produced two ways: added by hand here, or generated
 * by the solver over a date range (Phase 4). Generation will expand templates,
 * let the solver choose window-group days/times, and write the chosen shifts +
 * assignments as `autogenerated`, holding committed/performed items fixed.
 */

/** Add a one-off shift by hand. User-created shifts are firm (committed). */
export function addAdHocShift(input: {
  name: string;
  type?: string;
  start: string; // local ISO datetime
  durationMinutes: number;
}): string {
  const id = newId();
  mutate((d) =>
    d.ledgerShifts.push({
      id,
      name: input.name,
      type: input.type ?? "",
      start: input.start,
      durationMinutes: input.durationMinutes,
      status: "committed",
    }),
  );
  return id;
}

/**
 * Promote a shift and its assignments to committed — the user has taken
 * ownership, so the whole shift survives regeneration intact. `performed`
 * assignments are left as-is.
 */
function promote(d: AppData, shiftId: string): void {
  const s = d.ledgerShifts.find((x) => x.id === shiftId);
  if (s && s.status === "autogenerated") s.status = "committed";
  for (const a of d.ledgerAssignments) {
    if (a.ledgerShiftId === shiftId && a.status === "autogenerated") a.status = "committed";
  }
}

export function updateLedgerShift(id: string, patch: Partial<LedgerShift>): void {
  mutate((d) => {
    const s = d.ledgerShifts.find((x) => x.id === id);
    if (s) {
      Object.assign(s, patch);
      promote(d, id); // editing a shift locks it against regeneration
    }
  });
}

/** Delete a ledger shift and its assignments. */
export function removeLedgerShift(id: string): void {
  mutate((d) => {
    d.ledgerShifts = d.ledgerShifts.filter((s) => s.id !== id);
    d.ledgerAssignments = d.ledgerAssignments.filter((a) => a.ledgerShiftId !== id);
  });
}

// --- Assignments (manual edits auto-lock the shift) ------------------------

/** Assign a person to a shift (no duplicates). Manual edit → committed + lock. */
export function assignPerson(
  ledgerShiftId: string,
  personId: string,
  status: AssignmentStatus = "committed",
): void {
  mutate((d) => {
    const exists = d.ledgerAssignments.some(
      (a) => a.ledgerShiftId === ledgerShiftId && a.personId === personId,
    );
    if (!exists) d.ledgerAssignments.push({ ledgerShiftId, personId, status });
    promote(d, ledgerShiftId);
  });
}

export function unassignPerson(ledgerShiftId: string, personId: string): void {
  mutate((d) => {
    d.ledgerAssignments = d.ledgerAssignments.filter(
      (a) => !(a.ledgerShiftId === ledgerShiftId && a.personId === personId),
    );
    promote(d, ledgerShiftId);
  });
}

export function setAssignmentStatus(
  ledgerShiftId: string,
  personId: string,
  status: AssignmentStatus,
): void {
  mutate((d) => {
    const a = d.ledgerAssignments.find(
      (x) => x.ledgerShiftId === ledgerShiftId && x.personId === personId,
    );
    if (a) a.status = status;
    promote(d, ledgerShiftId);
  });
}

/** Annotate an assignment (e.g. substitution reason, no-show note). */
export function setAssignmentNote(ledgerShiftId: string, personId: string, note: string): void {
  mutate((d) => {
    const a = d.ledgerAssignments.find(
      (x) => x.ledgerShiftId === ledgerShiftId && x.personId === personId,
    );
    if (a) a.note = note === "" ? undefined : note;
    promote(d, ledgerShiftId);
  });
}

// --- Generation support (autogenerated lifecycle) --------------------------

/** Intervals where committed/performed people are already busy (no double-book). */
export interface BusyInterval {
  personId: string;
  start: number;
  end: number;
  /** Rest period after `end`, in ms (from the source template's break). */
  breakMs?: number;
}
export function busyIntervals(data: AppData): BusyInterval[] {
  const shiftById = new Map(data.ledgerShifts.map((s) => [s.id, s]));
  const breakByTemplate = new Map(data.shiftTemplates.map((t) => [t.id, t.breakMinutes]));
  const out: BusyInterval[] = [];
  for (const a of data.ledgerAssignments) {
    if (a.status === "autogenerated") continue;
    const s = shiftById.get(a.ledgerShiftId);
    if (!s) continue;
    const start = new Date(s.start).getTime();
    const breakMin = (s.sourceTemplateId && breakByTemplate.get(s.sourceTemplateId)) || 0;
    out.push({
      personId: a.personId,
      start,
      end: start + s.durationMinutes * 60_000,
      breakMs: breakMin * 60_000,
    });
  }
  return out;
}

/**
 * Remove autogenerated shifts whose start is in [rangeStart, rangeEnd) and their
 * assignments, plus any autogenerated assignments on committed/performed shifts
 * in that range — clearing the way for a fresh regeneration. Leaves
 * committed/performed shifts and assignments intact. Returns counts.
 */
export function clearAutogeneratedInRange(rangeStart: Date, rangeEnd: Date): { shifts: number; assignments: number } {
  const startStr = fmtLocalDateTime(rangeStart);
  const endStr = fmtLocalDateTime(rangeEnd);
  const inRange = (s: string) => s >= startStr && s < endStr;
  let shifts = 0;
  let assignments = 0;
  mutate((d) => {
    const removedShiftIds = new Set<string>();
    d.ledgerShifts = d.ledgerShifts.filter((s) => {
      if (s.status === "autogenerated" && inRange(s.start)) {
        removedShiftIds.add(s.id);
        shifts++;
        return false;
      }
      return true;
    });
    const startById = new Map(d.ledgerShifts.map((s) => [s.id, s.start]));
    d.ledgerAssignments = d.ledgerAssignments.filter((a) => {
      if (removedShiftIds.has(a.ledgerShiftId)) {
        assignments++;
        return false;
      }
      // Also drop tentative assignments on surviving shifts in range.
      if (a.status === "autogenerated") {
        const start = startById.get(a.ledgerShiftId);
        if (start !== undefined && inRange(start)) {
          assignments++;
          return false;
        }
      }
      return true;
    });
  });
  return { shifts, assignments };
}

/** Promote every autogenerated shift and assignment to committed (finalize). */
export function commitAllAutogenerated(): number {
  let count = 0;
  mutate((d) => {
    for (const s of d.ledgerShifts) if (s.status === "autogenerated") { s.status = "committed"; count++; }
    for (const a of d.ledgerAssignments) if (a.status === "autogenerated") { a.status = "committed"; count++; }
  });
  return count;
}

// --- Prior load (history for workload/variety) -----------------------------

export interface PersonLoad {
  shifts: number;
  minutes: number;
}

/**
 * Per-person committed + performed load read from the Ledger — the history that
 * keeps someone already booked ahead from being over-loaded. With `asOf`, only
 * counts shifts starting before that moment.
 */
export function priorLoad(data: AppData, asOf?: Date): Map<string, PersonLoad> {
  const shiftById = new Map(data.ledgerShifts.map((s) => [s.id, s]));
  const cutoff = asOf ? fmtLocalDateTime(asOf) : undefined;
  const load = new Map<string, PersonLoad>();
  for (const a of data.ledgerAssignments) {
    if (a.status !== "committed" && a.status !== "performed") continue;
    const shift = shiftById.get(a.ledgerShiftId);
    if (!shift) continue;
    if (cutoff && shift.start >= cutoff) continue;
    const cur = load.get(a.personId) ?? { shifts: 0, minutes: 0 };
    cur.shifts += 1;
    cur.minutes += shift.durationMinutes;
    load.set(a.personId, cur);
  }
  return load;
}

// --- Reconciliation --------------------------------------------------------

export interface AvailabilityConflict {
  ledgerShiftId: string;
  personId: string;
  personName: string;
  shiftName: string;
  start: string;
}

/**
 * Find committed/performed assignments that now fall outside the person's
 * effective availability (e.g. after adding an unavailable interval). Surfaced
 * to the user rather than silently dropped.
 */
export function reconcileAvailability(data: AppData): AvailabilityConflict[] {
  const shiftById = new Map(data.ledgerShifts.map((s) => [s.id, s]));
  const personById = new Map(data.persons.map((p) => [p.id, p]));
  const conflicts: AvailabilityConflict[] = [];
  for (const a of data.ledgerAssignments) {
    if (a.status === "autogenerated") continue;
    const shift = shiftById.get(a.ledgerShiftId);
    if (!shift) continue;
    if (!isPersonAvailable(data, a.personId, new Date(shift.start))) {
      conflicts.push({
        ledgerShiftId: a.ledgerShiftId,
        personId: a.personId,
        personName: personById.get(a.personId)?.name ?? "?",
        shiftName: shift.name,
        start: shift.start,
      });
    }
  }
  return conflicts;
}
