/**
 * generate.ts — drive a roster generation end to end: build the model from the
 * current dataset + range, solve it in the worker, and write the result into the
 * Ledger as `autogenerated` shifts + assignments.
 *
 * Regeneration semantics (v1): autogenerated shifts/assignments in the range are
 * cleared and replaced; committed/performed shifts are left untouched and their
 * people are treated as busy so they're never double-booked. A generated shift
 * that coincides with an existing committed shift (same template + start) is
 * skipped, so locked shifts aren't duplicated.
 */

import { getAppData, newId } from "../model/store";
import { mutate } from "../model/mutations";
import { busyIntervals, clearAutogeneratedInRange } from "../model/ledger";
import { buildModel, interpretSolution } from "./formulation";
import type { GenerateResult } from "./formulation";
import { solveLP } from "./solve";

export interface GenerateSummary {
  status: string;
  shiftsCreated: number;
  assignmentsCreated: number;
  instancesConsidered: number;
}

export async function generateRoster(rangeStart: Date, rangeEnd: Date): Promise<GenerateSummary> {
  const data = getAppData();
  const ctx = buildModel(data, rangeStart, rangeEnd, busyIntervals(data));
  const solution = await solveLP(ctx.lp);
  const result = interpretSolution(solution, ctx);
  return applyGeneration(result, rangeStart, rangeEnd);
}

/**
 * Write a solved result into the Ledger: clear tentative content in range, then
 * add autogenerated shifts (skipping any that coincide with a committed shift)
 * and their assignments. Separated from solving so it is testable without the
 * worker.
 */
export function applyGeneration(result: GenerateResult, rangeStart: Date, rangeEnd: Date): GenerateSummary {
  clearAutogeneratedInRange(rangeStart, rangeEnd);

  const surviving = getAppData();
  const committedKeys = new Set(
    surviving.ledgerShifts
      .filter((s) => s.status !== "autogenerated")
      .map((s) => `${s.sourceTemplateId ?? ""}@${s.start}`),
  );

  const instanceToShiftId = new Map<string, string>();
  let shiftsCreated = 0;
  let assignmentsCreated = 0;

  mutate((d) => {
    for (const sh of result.shifts) {
      if (committedKeys.has(`${sh.templateId}@${sh.start}`)) continue; // already locked
      const id = newId();
      instanceToShiftId.set(sh.instanceId, id);
      d.ledgerShifts.push({
        id,
        name: sh.name,
        type: sh.type,
        start: sh.start,
        durationMinutes: sh.durationMinutes,
        status: "autogenerated",
        sourceTemplateId: sh.templateId,
      });
      shiftsCreated++;
    }
    for (const as of result.assignments) {
      const shiftId = instanceToShiftId.get(as.instanceId);
      if (!shiftId) continue;
      d.ledgerAssignments.push({ ledgerShiftId: shiftId, personId: as.personId, status: "autogenerated" });
      assignmentsCreated++;
    }
  });

  return {
    status: result.status,
    shiftsCreated,
    assignmentsCreated,
    instancesConsidered: result.instancesConsidered,
  };
}
