/**
 * Throwaway check of the Ledger exporters: CSV + iCalendar. Verifies end-time
 * math, escaping (a comma in a name, a note), an unassigned shift, and basic
 * ICS structure.
 *
 * Run: npx tsx scripts/export.mts
 */
import { AppDataSchema, SCHEMA_VERSION } from "../src/model/schema";
import { ledgerToCsv, ledgerToIcs } from "../src/persistence/export";
import type { AppData } from "../src/model/types";

const data: AppData = AppDataSchema.parse({
  meta: { schemaVersion: SCHEMA_VERSION, appVersion: "0.0.0" },
  persons: [{ id: "A", name: "Ann, RN", activated: true }, { id: "B", name: "Bo", activated: true }],
  ledgerShifts: [
    { id: "s1", name: "Night; ward", type: "night", start: "2026-01-02T22:00:00", durationMinutes: 600, status: "committed" },
    { id: "s2", name: "Day", type: "day", start: "2026-01-01T09:00:00", durationMinutes: 480, status: "performed" },
    { id: "s3", name: "Empty", type: "", start: "2026-01-03T09:00:00", durationMinutes: 120, status: "autogenerated" },
  ],
  ledgerAssignments: [
    { ledgerShiftId: "s1", personId: "A", status: "committed" },
    { ledgerShiftId: "s2", personId: "A", status: "performed", note: "covered for Bo" },
    { ledgerShiftId: "s2", personId: "B", status: "performed" },
  ],
}) as AppData;

console.log("===== CSV =====");
console.log(ledgerToCsv(data));
console.log("\n===== ICS =====");
const ics = ledgerToIcs(data, new Date("2026-06-11T12:00:00Z"));
console.log(ics);

// Basic structural assertions.
const checks: [string, boolean][] = [
  ["VCALENDAR wrapped", ics.startsWith("BEGIN:VCALENDAR") && ics.trimEnd().endsWith("END:VCALENDAR")],
  ["3 VEVENTs", (ics.match(/BEGIN:VEVENT/g) || []).length === 3],
  ["night DTSTART local", ics.includes("DTSTART:20260102T220000")],
  ["night DTEND +10h", ics.includes("DTEND:20260103T080000")],
  ["semicolon escaped in summary", ics.includes("SUMMARY:Night\\; ward")],
  ["CRLF line endings", ics.includes("\r\n")],
  ["CSV comma-name quoted", ledgerToCsv(data).includes('"Ann, RN"')],
  ["CSV chronological (Day first)", ledgerToCsv(data).split("\r\n")[1].startsWith("Day,")],
];
console.log("\n===== checks =====");
for (const [label, ok] of checks) console.log(`${ok ? "PASS" : "FAIL"}  ${label}`);
process.exit(checks.every(([, ok]) => ok) ? 0 : 1);
